import turtle
screen = turtle.Screen()
screen.title("Lord Hanuman Sketch")
screen.bgcolor("#F5DEB3")
hanuman = turtle.Turtle()
hanuman.speed(2)
hanuman.pensize(4)
hanuman.penup()
hanuman.goto(0, 100)
hanuman.pendown()
hanuman.circle(100)
hanuman.penup()
hanuman.goto(-30, 140)
hanuman.fillcolor("black")
hanuman.begin_fill()
hanuman.circle(10)
hanuman.end_fill()
hanuman.penup()
hanuman.goto(30, 140)
hanuman.begin_fill()
hanuman.circle(10)
hanuman.end_fill()
hanuman.penup()
hanuman.goto(-40, 70)
hanuman.pendown()
hanuman.right(45)
hanuman.forward(50)
hanuman.left(90)
hanuman.forward(50)
hanuman.right(45)
hanuman.penup()
hanuman.goto(-100, 180)
hanuman.pendown()
hanuman.left(60)
hanuman.forward(50)
hanuman.right(120)
hanuman.forward(50)
hanuman.left(60)
hanuman.penup()
hanuman.goto(50, 180)
hanuman.pendown()
hanuman.right(60)
hanuman.forward(50)
hanuman.left(120)
hanuman.forward(50)
hanuman.right(60)
hanuman.penup()
hanuman.goto(-100, 0)
hanuman.pendown()
hanuman.fillcolor("#8B4513")
hanuman.begin_fill()
hanuman.right(90)
hanuman.forward(150)
hanuman.left(120)
hanuman.forward(220)
hanuman.left(120)
hanuman.forward(220)
hanuman.left(120)
hanuman.forward(150)
hanuman.end_fill()
hanuman.penup()
hanuman.goto(-210, 110)
hanuman.pendown()
hanuman.fillcolor("#8B4513")
hanuman.begin_fill()
hanuman.right(30)
hanuman.forward(80)
hanuman.left(120)
hanuman.forward(80)
hanuman.left(120)
hanuman.forward(80)
hanuman.end_fill()
hanuman.penup()
hanuman.goto(130, 110)
hanuman.pendown()
hanuman.fillcolor("#8B4513")
hanuman.begin_fill()

